### ISSUE TITLE
mark inactive applications in search overview

### ISSUE THREAD

**Issue by drummerwolli** [zalando-stups/yourturn#184]
it would be nice to see in the overview list already, if an application is inactive or not. makes it easier to depict, which ID is the real one to use ...

**Comment by prayerslayer** [comment]
Sounds reasonable :+1:

**Comment by prayerslayer** [comment]
Inactive apps are gray and have a badge next to it.

![image](https://cloud.githubusercontent.com/assets/878512/8412736/11d17e58-1e8c-11e5-8efd-855992d58af9.png)
