### ISSUE TITLE
Provide user feedback when loading data / being not authenticated

### ISSUE THREAD

**Issue by hjacobs** [zalando-stups/yourturn#195]
YOUR TURN currently provides no visual feedback that data is still being loaded (or authorization needs to be done) - only the browser loading indicator is shown (tiny icon in tab). See the attached screenshot - it looks like I have no applications, but actually I'm waiting for the "redirect" to the OAuth provider to happen...
This is especially "annoying" (or confusing) if the user's internet connection is slow.

![yourturn-loading](https://cloud.githubusercontent.com/assets/510328/8543540/bdeca1ce-249d-11e5-9321-634f4f24b79e.png)

**Comment by prayerslayer** [comment]
Fixed with #252
