### ISSUE TITLE
npm install fails due to missing zalando/node-scm-source dependency

### ISSUE THREAD

**Issue by hjacobs** [zalando-stups/yourturn#294]
The "npm i" command stated in the README  will not work out of the box due to a missing dependency:
```
npm http 404 https://registry.npmjs.org/zalando/node-scm-source/0.2.2
npm ERR! 404 'zalando' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 3.13.0-34-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "i"
npm ERR! cwd /home/hjacobs/workspace/yourturn
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! code E404

**Comment by prayerslayer** [comment]
Sorry, typo. It’s `@zalando/node-scm-source`.

**Comment by prayerslayer** [comment]
Looking more closely I found that package.json contains the correct package: https://github.com/zalando-stups/yourturn/blob/7115aa5154a50d024cb8cc86e9e99d3d55d09cbe/package.json#L40

Could you try again with a recent version of npm (`2.x`)?

**Comment by prayerslayer** [comment]
Confirmed that it's an issue with NPM 1.x.
