### ISSUE TITLE
Auto Fill Mint Bucket

### ISSUE THREAD

**Issue by Jan-M** [zalando-stups/yourturn#316]
Please auto fill the Mint Bucket for new applications.

This is imho a common error/problem that is "hard" to detect and with the AWS startup time annoying to fix/waste time on.

**Comment by prayerslayer** [comment]
I’m hesitant to do auto-creation magic. Instead I could suggest a bucket and give you a button to add it with one click.

~~~
[ insert bucket input ] [+ add]
(if buckets.empty()
  Hey, your mint bucket is probably (getDefaultBucket(app.team_id)). [+ add])
[ empty list of buckets ]
~~~

Okay or half-assed? 😉

**Comment by Jan-M** [comment]
As long as I am as a user hinted at adding this bucket with an auto suggest value that makes sense I am happy. Basically a don't want to have a second flow or step to create a working application.

**Comment by prayerslayer** [comment]
Alright :+1: 

LET'S DO THIS THEN :godmode:
