### ISSUE TITLE
Make applications deletable is no version was ever created for them

### ISSUE THREAD

**Issue by MrSnoode** [zalando-stups/yourturn#319]
I have accidentally created an application in the wrong account (hackweek instead of team). Now the application Id is taken and I cannot create the application in the proper account without breaking our naming scheme. It seems unnecessary to keep application that no version was ever created for around forever.

**Comment by prayerslayer** [comment]
You can change the team if you edit the application (provided you have access to both the old and new account).

**Comment by MrSnoode** [comment]
That worked, thanks! You might still want to consider making applications with no versions deletable, but it is probably not a very high priority :-)

**Comment by prayerslayer** [comment]
Great, I’ll close this then.
