### ISSUE TITLE
Verify proper git url when entering

### ISSUE THREAD

**Issue by Jan-M** [zalando-stups/yourturn#321]
Seems fullstup looks for https:// url, but one can add a valid git@... url. this leads to unnecessary violation.

**Comment by prayerslayer** [comment]
1. There's a `https` placeholder already suggesting a HTTPS url.
2. This should actually not happen, try putting a repo's git url into [this fiddle](https://jsfiddle.net/qdvrx05n/) without the input turning red.
3. I can't verify this in prod:

![image](https://cloud.githubusercontent.com/assets/878512/10525127/4d502faa-7383-11e5-805e-bcfdc3c81b7a.png)

So either this is a browser bug or you can make the form accept a git@ url with some twists. Will investigate but in either case need more information.

**Comment by prayerslayer** [comment]
Works if you put `ssh://` or any protocol or bogus like `asdf://` in front.
