### ISSUE TITLE
Violations: improve filtering

### ISSUE THREAD

**Issue by nsmolenskii** [zalando-stups/yourturn#326]
**As** Deploy engineer
**I want** to have flexible filters to work with violations
**So that** made this future more usable

**Currently I can't:**
- Filter violations by type
- Filter violation by resolution (manually solved)
- Order violations by creation time

**It's will be much better to see by default only unresolved violations ordered by created time desc**

**Comment by hjacobs** [comment]
See also #304

**Comment by prayerslayer** [comment]
Ya, no worries, we’re on it and it’s high priority. There are just no real tickets yet.

Stay tuned :sunglasses:
