### ISSUE TITLE
Violations: Change sort order

### ISSUE THREAD

**Issue by prayerslayer** [zalando-stups/yourturn#354]
Currently violations are sorted from old to new, thinking was that people should resolve their old violations before they see new ones. However in some cases it might be helpful to see new ones first.

**Comment by hjacobs** [comment]
:tada: yes, I personally would like to see the most recent violations first (as they are more "relevant" and I can quickly react on things going wrong) --- obviously in the ideal world :earth_americas:  only a few violations exist and sort order is not important :smirk:
