### ISSUE TITLE
show/hide inactive apps

### ISSUE THREAD

**Issue by kolja** [zalando-stups/yourturn#355]
Add an option to show/hide applications that are flagged as inactive.

If the number of inactive apps grows too large, they may may start to become unnecessary, annoying visual clutter. It would be desirable to have an option that toggles visibility of those list-entries.

**Comment by prayerslayer** [comment]
:+1:

On 5 November 2015 at 14:56, Kolja <notifications@github.com> wrote:

> Add an option to show/hide applications that are flagged as inactive.
>
> If the number of inactive apps grows too large, they may may start to
> become unnecessary, annoying visual clutter. It would be desirable to have
> an option that toggles visibility of those list-entries.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zalando-stups/yourturn/issues/355>.
>



-- 

undefined = () => {}

(o_
//\

V_/_  Nikolaus Piccolotto
      engineer.js

**Comment by prayerslayer** [comment]
Done with #357
