### ISSUE TITLE
Use account name in stead of id in violation cards

### ISSUE THREAD

**Issue by prayerslayer** [zalando-stups/yourturn#387]
So that it's more understandable.

**Comment by hjacobs** [comment]
Please make sure I can also see the AWS account ID (I often need it..)

**Comment by prayerslayer** [comment]
Ok, will do. :+1:

On 1 December 2015 at 10:49, Henning Jacobs <notifications@github.com>
wrote:

> Please make sure I can also see the AWS account ID (I often need it..)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zalando-stups/yourturn/issues/387#issuecomment-160915748>
> .
>



-- 

undefined = () => {}

(o_
//\

V_/_  Nikolaus Piccolotto
      engineer.js
