### ISSUE TITLE
Application list slow

### ISSUE THREAD

**Issue by prayerslayer** [zalando-stups/yourturn#388]
Apparently one cannot click on other links while app versions are loading. Investigate.

**Comment by prayerslayer** [comment]
This is due to hundreds callbacks from calls to `kio/apps/:app/versions`, each taking 70–100 ms and blocking the UI thread. Making callbacks faster would not really help as 10s of waiting would be replaced by 5s of waiting. To make this really snappy we have to reduce those hundreds of calls to one or a few.

Solution:

* Group applications by team as roughly described in #386. Requests are then only made per team.
* Cache latest versions from Kio in YOUR TURN backend and provide an endpoint to get latest versions by team. => #391

**Comment by sarnowski** [comment]
Other possible solutions might include providing a bulk-read API in Kio to retrieve those versions.

**Comment by prayerslayer** [comment]
Not very RESTful and very frontend-specific though, so I'd rather not do that.
